#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""average image values"""

import sys
import typing
from warnings import filterwarnings as filter_warnings

import matplotlib.colors
import numpy
from PIL import Image


def main() -> int:
    """entry / main function"""

    image: typing.Any = Image.open(sys.argv[1])

    if image.mode != "RGBA":
        image = image.convert("RGBA")

    rgba: tuple[int, int, int, int] = tuple(
        numpy.mean(numpy.array(image.getdata()), axis=0)
    )

    print(
        f"rgba{rgba}",
        matplotlib.colors.to_hex(tuple(map(lambda c: c / 255, rgba)), True),
    )

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"

    filter_warnings("error", category=Warning)
    raise SystemExit(main())
