#!/usr/bin/env python3
"""Base85 encode"""

import sys
from base64 import b85encode, b85decode


def main() -> int:
    """Entry/main function"""

    sys.argv.append("")

    data = sys.stdin.buffer.read()

    if sys.argv[1] == "-d":
        sys.stdout.write(b85decode(data).decode())
    else:
        sys.stdout.write(b85encode(data).decode())

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"
    sys.exit(main())
