#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""cloude api -- https://api.caipacity.com/"""

import hashlib
import sys
from datetime import datetime
from time import time
from typing import Any, Final, Generator
from warnings import filterwarnings as filter_warnings

import requests
import ujson  # type: ignore

API: Final[str] = "https://api.caipacity.com/v1/chat/completions"
USER_AGENT: Final[
    str
] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
(KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
PROXY: Final[
    str
] = "https://gimmeproxy.com/api/getProxy?post=true&get=true\
&user-agent=true&supportsHttps=true&protocol=http&minSpeed=20&curl=true"
KEY: str = "OVbi[TPN{S#)c{36%9?g;usl)CL"


def message(msg: str) -> dict[str, Any]:
    msg = msg.encode("unicode_escape").decode()
    t: str = str(round(datetime.utcnow().timestamp() * 1000))

    return {
        "d": datetime.utcfromtimestamp(int(t) / 1000).strftime("%Y-%m-%d"),
        "messages": [{"role": "user", "content": msg}],
        "t": t,
        "s": hashlib.sha256(f"{t}:{msg}:{KEY}:{len(msg)}".encode()).hexdigest(),
        "stream": True,
        "model": "gpt-3.5-turbo",
    }


def _request_ai(prompt: str) -> Generator[str, None, None]:
    response: requests.Response | None = None

    while response is None or not response.ok:
        response = requests.post(
            API,
            headers={
                "authorization": "Bearer free",
                "user-agent": USER_AGENT,
            },
            json=message(prompt),
            stream=True,
            timeout=5,
        )

    from_line: int = 1

    for line in response.iter_lines():
        line = line.decode().removeprefix("data: ")

        if not line.startswith("{"):
            continue

        msg: dict[str, Any] = ujson.loads(line)["choices"][0]

        if msg["finish_reason"] == "stop":
            return
        elif "content" not in msg["delta"]:
            continue

        yield msg["delta"]["content"][from_line:]
        from_line = 0


def request_ai(*args, **kwargs) -> Generator[str, None, None]:
    e_idx: int = 0

    while True:
        try:
            yield from _request_ai(*args, **kwargs)
            break
        except (
            requests.exceptions.Timeout,
            requests.exceptions.ConnectionError,
            requests.exceptions.ProxyError,
        ) as err:
            if e_idx >= 10:
                raise err
            e_idx += 1


def main() -> int:
    """entry / main function"""

    prompt: str

    if len(sys.argv) < 2:
        return 1
    elif sys.argv[1] == "-":
        print("reading from stdin ...")
        prompt = sys.stdin.read()
        print("read")
    else:
        prompt = " ".join(sys.argv[1:])

    if not (prompt := prompt.strip()):
        return 2

    for msg in request_ai(prompt):
        print(msg, file=sys.stdout, flush=True, end="")

    print()

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"

    filter_warnings("error", category=Warning)
    filter_warnings("ignore", category=ResourceWarning)

    raise SystemExit(main())
