#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""chatgpt wrapper, bypasses all ( or most ) filters and ethics things"""

import os
import sys

import openai


def main() -> int:
    """Entry/main function"""

    if len(sys.argv) < 2:
        return 0

    with open(os.path.expanduser("~/Ari/passwd/openai.key")) as api_key:
        openai.api_key = api_key.readline().strip()

    print(
        openai.Completion.create(  # type: ignore
            model="code-cushman-001",
            prompt=" ".join(sys.argv[1:]),
            temperature=0.5,
            max_tokens=512,
            top_p=1.0,
            frequency_penalty=0.0,
            presence_penalty=0.0,
        )["choices"][0]["text"].strip()
    )

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"
    raise SystemExit(main())
