#!/usr/bin/env bash

urgent=(
    "low"
    "normal"
    "critical"
)

for i in "${!urgent[@]}";
do
    dunstify -u "${urgent[$i]}" "Notification summary for ${urgent[$i]}" \
        "This is a dunst notification test, this is this notification's body :)"
done

