#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gpt image"""

import sys
from warnings import filterwarnings as filter_warnings

import requests


def main() -> int:
    """entry / main function"""

    p: str = " ".join(sys.argv[1:]).strip()

    if not p:
        return 1

    with open("image.png", "wb") as fp:
        fp.write(
            requests.get(
                requests.post(
                    "https://apis.scrimba.com/openai/v1/images/generations",
                    json={
                        "model": "dall-e-3",
                        "prompt": p,
                        "n": 1,
                        "size": "1024x1024",
                    },
                ).json()["data"][0]["url"]
            ).content
        )

        print(f"generated {fp.name!r}")

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"

    filter_warnings("error", category=Warning)
    raise SystemExit(main())
