#!/usr/bin/env python3

import asyncio
import sys
import os
import random

from colorama import Fore


def scramble(target: list[str]) -> str:
    final = list("".join(target) if len(target) <= 1 else " ".join(target))
    random.shuffle(final)

    return "".join(final[::-1])


def debug(message: str, header: str = "DEBUG", colour: int = Fore.YELLOW) -> None:
    sys.stderr.write(
        f"{Fore.BLUE}[{colour}{header.upper()}{Fore.BLUE}]{Fore.RESET} {message}\n"
    )


async def main() -> int:
    sys.argv[0] = os.path.split(sys.argv[0])[1]

    if sys.stdin.isatty():
        if len(sys.argv) < 2:
            debug(f"{sys.argv[0]} <...strings>", "USAGE", Fore.MAGENTA)
            return 1

        final = sys.argv[1:]
    else:
        final = list(sys.stdin.read())

    print(scramble(final))

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"
    exit(asyncio.run(main()))
