#!/usr/bin/env sh

state="$(pacmd dump | grep "set-default-sink" | head -n1 | cut -d ' ' -f2 | xargs pacmd list-sinks | grep -q "muted: yes" && printf 'yes' || printf 'no')"

pactl set-sink-mute @DEFAULT_SINK@ yes
slock
pactl set-sink-mute @DEFAULT_SINK@ "$state"
