#!/usr/bin/env bash

main() {
    options=("1 Cancel"
        "2 Quit DWM"
        "3 Reboot"
        "4 Poweroff / Shutdown"
        "5 Kill xautolock")

    option="$(/usr/bin/printf "%s\n" "${options[@]}" | \dmenu | /usr/bin/awk '{ print $1 }')"

    [[ ! $option ]] && exit 1

    case "$option" in
    1) exit 0 ;;
    2) killall dwm ;;
    3) ${__BASH_RUNAS:-sudo} reboot -h ;;
    4) ${__BASH_RUNAS:-sudo} poweroff ;;
    5) xautolock -exit ;;
    *) notify-send "Option '$option' not found" ;;
    esac
}

main "$@"
