#!/bin/sh

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)

trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"

sed '/^\s*$/d' "$tmpfile" | dmenu -p 'Copy line:' | xclip -selection clipboard

