#!/usr/bin/env python3
"""load custom charsets"""

import sys
import os


CHARDIR = os.path.expanduser("~/.config/charsets")


def main() -> int:
    """Entry/main function"""
    if len(sys.argv) < 2:
        return 1

    if sys.argv[1] == "ls":
        for char in os.scandir(CHARDIR):
            sys.stderr.write(f" * {os.path.basename(char)}\n")
    else:
        characters = ""

        for charset in sys.argv[1:]:
            try:
                with open(f"{CHARDIR}/{charset}", "r") as full_charset:
                    characters += full_charset.read().strip("\n")
            except FileNotFoundError:
                characters += charset.strip("\n")

        sys.stdout.write("".join(set(characters)))

    return 0


if __name__ == "__main__":
    assert main.__annotations__.get("return") is int, "main() should return an integer"
    sys.exit(main())
