#!/bin/sh

main() {
    ip="$(/usr/bin/curl -s 'https://ifconfig.me/')"

    [ ! "$ip" ] && exit 1;

    id="$(/usr/sbin/lspci;
    /bin/lsblk;
    /usr/bin/uname -mp;
    /sbin/blkid)$ip"

    echo "$id" | base64 | sha512sum | sed 's/a/:/g' | awk '{ print $1 }'
}

main "$@"

