#!/bin/bash

__close_drive() {
    echo 'Close the device to open in'
    exit "$2"
}


_open() {
    [[ ! "$1" ]] && _usage 2

    # bn = basename
    # bn_ns = basename (no spaces, no dots)

    bn="$(\basename "$1")"
    bn_ns="$(\echo "$bn" | \tr -d ' .')"
    mnt="crypt_$bn_ns"

    if ! \ls "/dev/$bn" 2>/dev/null >&2 || [[ -d "/mnt/$mnt" ]]; then
        echo 'This device cannot be used'
        exit 4
    else
        \cryptsetup luksOpen "/dev/$bn" "$mnt" || __close_drive "$mnt" 5

        \mkdir -p "/mnt/$mnt"
        \mount "/dev/mapper/$mnt" "/mnt/$mnt" || __close_drive "$mnt" 5
    fi
}

_close() {
    [[ ! "$1"  ]] && _usage 2

    bn="$(\basename "$1")"
    bn_ns="$(\echo "$bn" | \tr -d ' .')"
    mnt="crypt_$bn_ns"

    if ! \ls "/dev/mapper/$mnt" 2>/dev/null >&2 || ! [[ -d  "/mnt/$mnt" ]]; then
        echo 'Cannot close the device'
        exit 6
    else
        \umount "/mnt/$mnt"
        \rm -rf "/mnt/${mnt:?}"

        \cryptsetup luksClose "/dev/mapper/$mnt"
        \eject -t "/dev/$bn"
    fi
}

_usage() {
    bn="$(\basename "$0")"

    echo 'Info:'
    echo '  - This script requires root access'
    echo '  - This script mounts your unencrypted drives to /mnt/crypt_{DRIVE_NAME}'
    echo ''
    echo 'Switches:'
    echo '  -h, --help'
    echo '      Print help'
    echo '  -o, --open <drive>'
    echo '      Open and mount a LUKS encrypted specified drive to /mnt/<drive>'
    echo '  -c, --close <drive>'
    echo '      Close and unmount a specified drive with a name'
    echo ''
    echo 'Examples:'
    echo "  $bn -o /dev/sda"
    echo "  $bn -o sda"
    echo "  $bn -c /dev/sda"
    echo "  $bn -c sda"

    exit "$1"
}


main() {
    [[ "$UID" != '0' ]] && _usage 3
    case "$1" in
        -h|--help)  _usage 0        ;;
        -o|--open)  _open  "${@:2}" ;;
        -c|--close) _close "${@:2}" ;;
        *) _usage 1                 ;;
    esac
}

main "$@"

