#!/usr/bin/env bash

main() {
    read -p '(VM NAME) ' vm_name
    mkdir "$vm_name"
    cd "$vm_name" || exit 1

    read -p '(DISK SIZE N[K,G,...]) ' disk_size
    read -p '(DISK FORMAT) ' disk_format
    qemu-img create -f "$disk_format" 'root.img' "$disk_size"

    read -p '(CD-ROM) ' cdrom
    read -p '(RAM [M]) ' ram
    read -p '(CPU) ' cpu
    read -p '(ARCH) ' arch
    read -p '(UEFI [on/off]) ' uefi

    echo '#!/bin/sh' | tee -a run
    echo "'qemu-system-${arch}' -smbios type=0,uefi=$(echo "$uefi" | cut -d' ' -f 1) -cpu host -enable-kvm -m '${ram}' -smp '${cpu}' -drive file='root.img',format='${disk_format}'" | tee -a run
    chmod +rx run

    "qemu-system-$arch" -smbios type=0,uefi="$uefi" -cdrom "$cdrom" -cpu host -enable-kvm -m "$ram" -smp "$cpu" -drive file='root.img',format="$disk_format"
}

main "$@"

