#!/bin/sh

main() {
    reset="\e[0m"
    red="\e[0;91m"
    green="\e[0;92m"
    cyan="\e[0;36m"

    printf "${red}[*] Explicit${reset}: %s\n" "$(wc -l </var/lib/portage/world)"
    printf "${cyan}[*] Orphans${reset}: %s\n" "$(emerge -cp  2>/dev/null | grep -io '^[a-z]\S*:' | wc -l)"
    printf "${green}[*] Total${reset}: %s\n" "$(equery list '*' | wc -l)"
}

main "$@"

