#!/bin/bash

main() {
    if [ ! "$1" ]; then
        local max_length=$((RANDOM % 384))
    else
        local max_length="$(($1 + 1 + RANDOM % 6))"
    fi

    local rng="$(( (50 + RANDOM) % "$max_length"))"

    dd if=/dev/urandom of=/tmp/.pwdgen_random_bytes bs=1 count="$rng" status=none
    date >>/tmp/.pwdgen_random_bytes

    id="${RANDOM}$(lsblk -fa | rev;
        date | sha512sum;
        ip a | rev | base64 | md5sum;
        which "$SHELL" | base32;
        env;
        ps aux | sha256sum;
        ss | sha384sum)${RANDOM}"

    echo "$id" >>/tmp/.pwdgen_random_bytes

    local bytes
    bytes="${RANDOM}$(cat -A /tmp/.pwdgen_random_bytes)大波留${id}${RANDOM}"

    echo -en "$(((RANDOM / max_length) * max_length ^ WINDOWID))${bytes}${COLUMNS}${max_length}${id}
                $(date '+%N%S%N%u%V%N%y%Y%m%G%I%m%N%s%N')${bytes,,}$(ip a | sha384sum)${WINDOWID}${PS1}${RANDOM}" |
        base64 -w 0 --ignore-garbage |
        sed 's/O/k/g; s/=/{/g; s/U/s/g; s/4/%/g; s/G/O/g; s/g/4/g; s/s/p/g; s/T/=/g; s/R/*/g' |
        base32 -w 0 --ignore-garbage |
        sha512sum |
        edonr512-hash - |
        sed 's/5/p/g; s/e/G/g; s/c/5/g; s/b/c/g; s/c/H/g; s/9/e/g' |
        base64 -w 0 --ignore-garbage |
        sed 's/_/O/g; s/d/_/g; s/A/@/g; s/E/:/g' |
        base64 -w 0 --ignore-garbage |
        rev |
        tail --bytes="$((30 + rng + ((RANDOM % max_length) - 20)))" |
        sed 's/\//F/; s/=//g; s/8/u/g; s/p/*/g; s/U/%/g; s/f/-/g; s/s/@/g; s/Y/+/g'  |
        sed 's/e/&/g; s/O/./g; s/W/~/g; s/m/\\/; s/~/l/g; s/9/$/; s/o/:/g; s/K/`/g'  |
        awk '{ print $1 }' |
        rev

    rm -f /tmp/.pwdgen_random_bytes
}


main "$@"

