#!/bin/bash

main() {
    if [ ! "$1" ] || [ ! "$2" ]; then
        echo "$(basename "$0") <count> <length>"
        exit 1
    fi

    local passwords=()
    for _ in $(seq 1 "$1"); do
        passwords+=("$(pwdgen "$2")")
    done

    printf "%s\n" "${passwords[@]}" |
        fzf --layout=reverse --height=20 --no-mouse -i |
        tr -d "\n" |
        xclip -sel c
}

main "$@"

