#!/bin/sh

main() {
    calcurse --next |
        tr -d "\n\[\]" |
        awk '{ print $4 " in " $3 }' |
        xargs -0 dunstify -u critical 'Calcurse reminder'

    # Beep
    (speaker-test -l 1 -f 1500 -t sine -P 2 -X >/dev/null)& pid="$!"; sleep 0.08; kill -9 $pid

    return 0
}

main "$@"

