// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1634834306);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1634834277);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1634834336);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1634834275);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 117);
user_pref("browser.newtabpage.activity-stream.impressionId", "{96bea790-1f61-4900-a64e-606ba89eb1e3}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1634834277);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1634834287016");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1634855887016");
user_pref("browser.search.region", "LT");
user_pref("browser.startup.homepage_override.buildID", "20211021033811");
user_pref("browser.startup.homepage_override.mstone", "93.0");
user_pref("browser.startup.lastColdStartupCheck", 1634834276);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1634834277860");
user_pref("distribution.gentoo.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "93.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "LT");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20211021033811");
user_pref("extensions.lastAppVersion", "93.0");
user_pref("extensions.lastPlatformVersion", "93.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"7ec939ee-d9f3-451c-a85f-7f13748f7bdb\",\"formautofill@mozilla.org\":\"73b8ec0e-bf5e-402f-a25b-5a0d5a2bf795\",\"pictureinpicture@mozilla.org\":\"903482b2-8db7-42b0-822d-2bb2a8fb8616\",\"screenshots@mozilla.org\":\"d60eaed0-99c2-47a4-a3e3-511dad1da84b\",\"webcompat-reporter@mozilla.org\":\"f83c3830-8bba-4c22-aacd-0fe7443bba9b\",\"webcompat@mozilla.org\":\"6ad2a787-16b0-417b-842b-1fb64d023428\",\"default-theme@mozilla.org\":\"30203e85-f6bc-48cc-9ce0-7224ba6c3ce9\",\"google@search.mozilla.org\":\"41206e7b-9c20-4f0c-8051-8b8774c91c85\",\"amazondotcom@search.mozilla.org\":\"5db99c13-ef90-40d9-ae06-b427b35cbde5\",\"wikipedia@search.mozilla.org\":\"28293fef-1109-4f2a-b4bf-04c4a564667f\",\"bing@search.mozilla.org\":\"71cbf6c8-9746-4e0e-b4ac-95b39863adad\",\"ddg@search.mozilla.org\":\"996b1ade-d7f7-42c4-a094-f42807b0fa72\",\"{8ff2d753-2dc8-46de-a837-fa28331d9fcf}\":\"9b2089de-d2f2-4c33-81ba-3ab299c03781\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1634834277);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp-manager.buildID", "20211021033811");
user_pref("media.gmp-manager.lastCheck", 1634834297);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":null,\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8127730c-1471-429c-bc7a-9799039df93b");
user_pref("toolkit.startup.last_success", 1634834275);
user_pref("toolkit.telemetry.cachedClientID", "b1150303-12a6-42a4-a505-3d48194be899");
user_pref("toolkit.telemetry.previousBuildID", "20211021033811");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
