#!/usr/bin/env bash

set -e

main() {
    RESET="\e[0m"
    BOLD="\e[1m"
    GREEN="\e[32m"
    RED='\033[00;31m'

    for directory in *; do
        if [[ -d $directory ]]; then
            echo -en "\n${BOLD}>> ${RESET}Compiling ${GREEN}$directory${RESET}\n\n"

            chown "$USER":"$USER" -R "$directory"

            make -C "$directory" clean
            make -C "$directory" -j"$(($(nproc --all) * 4))"
            make_return_code="$?"

            "${__BASH_RUNAS:-sudo}" make -C "$directory" install

            if [[ $make_return_code -ne '0' ]]; then
                echo -e "${BOLD}${RED}!!${RESET} ${BOLD}make${RESET} exited with code of ${BOLD}$make_return_code${RESET}"
                exit 1
            fi
        fi
    done
}

main "$@"
