#!/bin/bash

back=$(pwd)

for i in ./*;
do
    if [[ -d "$i"  ]];
    then
        echo -en "\n$i\n\n"
        cd $i
        sudo make clean install
        b="$?"
        cd $back

        if [[ "$b" != 0 ]]; then
            break
        fi

        unset b
    fi
done

unset back
unset i

