#!/bin/bash

back=$(pwd)

for i in ./*;
do
    if [[ -d "$i"  ]]; then
        echo -en "\n$i\n\n"
        cd "$i" || exit 1
        sudo make clean install
        b="$?"
        cd "$back" || exit 1

        if [[ "$b" -ne '0' ]]; then
            break
        fi

        unset b
    fi
done

unset back
unset i

