scriptencoding utf-8

syntax on                       " turn syntax highlighting on
filetype plugin on              " this makes vim invoke latex-suite when you open a tex file
filetype plugin indent on       " enable filetype-specific indents

set nocompatible                " no need for vi
set noerrorbells                " turn off error sound
set expandtab smarttab          " will make the tab key insert spaces instead of tabs
set smartindent autoindent      " automatically indent files
set number relativenumber       " show line count in a file (dynamic)
set nowrap                      " turn word wrapping off
set ignorecase                  " turn case-insensitive searching on
set noswapfile                  " turn swap files off
set nobackup                    " don't back files up after saving the file
set undofile                    " let undo get stored in files
set incsearch                   " show results while searching live
set confirm                     " confirm unsaved changes in files
set lazyredraw                  " remove macro redraws
set autochdir                   " automatically enter a directory if a file is opened
set cursorline                  " highlight the current line number
set splitright                  " split the terminal to below and split files to right
set timeout                     " let timeout happen
set noeol                       " add a newline
set wildmenu                    " enable command mode autocomplete
set list                        " enable visible whitespace

set encoding=utf-8              " file encoding
set laststatus=2                " set the bar type
set undodir=~/.vim/undodir      " where to put undo files
set tabstop=4                   " maximum tab width
set shiftwidth=4                " indent size
set softtabstop=0               " insert spaces instead of tabs
set guicursor=a:hor100          " set the cursor shape to a _
set clipboard=unnamedplus       " copy text to clipboard
set timeoutlen=0 ttimeoutlen=0  " set timeout to 0s
set virtualedit=all             " improve visual block to select past the line
set backspace=0                 " disable backspace
set t_Co=256                    " show 256 colours
set viminfofile=~/.vim/.viminfo " store viminfo
set nrformats-=octal            " remove octal format from numbers ( bc its stupid )
set fileformat=unix             " unix >>>
                                " make `set list` pretty
set listchars=trail:~,extends:»,precedes:«,nbsp:×

" plugins
"   To Install the plugins type `:PlugInstall`
" CoC:
"   $ cd ~/.vim/plugged/coc.nvim
"   $ npm install
" Bracey:
"   $ cd ~/.vim/plugged/bracey.vim # TruncatedDinosour/dotfiles-cleaned #4
"   $ npm install --prefix server

" function! BuildVimComposer(info)
"     if a:info.status != 'unchanged' || a:info.force
"         if has('nvim')
"             silent !cargo build --release --locked
"         else
"             silent !cargo build --release --locked --no-default-features --features json-rpc
"         endif
"     endif
" endfunction

call plug#begin("~/.vim/plugged")
    Plug 'turbio/bracey.vim'
    Plug 'mattn/emmet-vim'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'w0rp/ale'
    Plug 'coffee-theme/lightline.vim'
    Plug 'vim-latex/vim-latex'
    Plug 'google/vim-maktaba'
    Plug 'TruncatedDinosour/vim-codefmt'
    Plug 'Yggdroot/indentLine'
    Plug 'drmingdrmer/vim-tabbar'
    Plug 'lilydjwg/colorizer'
    Plug 'christoomey/vim-tmux-navigator'
    Plug 'tpope/vim-surround'
    Plug 'editorconfig/editorconfig-vim'
    Plug 'haya14busa/is.vim'
    Plug 'machakann/vim-highlightedyank'
    Plug 'luochen1990/rainbow'
    Plug 'coffee-theme/coffee.vim'
    Plug 'TruncatedDinosour/vimbuddy.vim'
    Plug 'godlygeek/tabular'
    Plug 'fedorenchik/fasm.vim'
    Plug 'sheerun/vim-polyglot'
    Plug 'katusk/vim-qkdb-syntax'
    Plug 'tpope/vim-commentary'
    Plug 'TruncatedDinosour/subby.vim'
    Plug 'itchyny/vim-cursorword'
    Plug 'dstein64/vim-startuptime'
    Plug 'tpope/vim-endwise'
    Plug 'chiedo/vim-case-convert'
    Plug 'svermeulen/vim-subversive'
call plug#end()

" Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown', 'do': 'npm install'}
" Plug 'euclio/vim-markdown-composer', { 'do': function('BuildVimComposer') }

colorscheme coffee                      " set the theme

" plugin config
source ~/.vim/pack/plugins/start/vimrc/plugin/plugin_config.vim

" filetypes
source ~/.vim/pack/plugins/start/vimrc/plugin/filetype.vim
